spring:
  application:
    name: gamyeon-backend
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

cloud:
  aws:
    region:
      static: ${AWS_REGION:ap-northeast-2}

jwt:
  access-token-expiry: 3600000
  refresh-token-expiry: 604800000

ai:
  server:
    url: ${AI_SERVER_URL:http://agent-server:8000}